const countries = [
  {
    name: 'India',
    states: [
      'Uttar Pradesh',
      'Maharashtra',
      'Bihar',
      'West Bengal',
      'Andhra Pradesh',
      'Tamil Nadu',
      'Karnataka',
      'Madhya Pradesh',
      'Rajasthan',
      'Gujarat',
    ],
  },
  {
    name: 'USA',
    states: [
      'California',
      'Texas',
      'Florida',
      'New York',
      'Pennsylvania',
      'Illinois',
      'Ohio',
      'Georgia',
      'North Carolina',
      'Michigan',
    ],
  },
  {
    name: 'China',
    states: [
      'Guangdong',
      'Shandong',
      'Henan',
      'Sichuan',
      'Jiangsu',
      'Hubei',
      'Hunan',
      'Anhui',
      'Shaanxi',
      'Jiangxi',
    ],
  },
  {
    name: 'Brazil',
    states: [
      'Sao Paulo',
      'Minas Gerais',
      'Rio de Janeiro',
      'Bahia',
      'Parana',
      'Rio Grande do Sul',
      'Pernambuco',
      'Ceara',
      'Para',
      'Santa Catarina',
    ],
  },
  {
    name: 'Russia',
    states: [
      'Moscow',
      'Saint Petersburg',
      'Novosibirsk Oblast',
      'Sverdlovsk Oblast',
      'Chelyabinsk Oblast',
      'Omsk Oblast',
      'Samara Oblast',
      'Krasnoyarsk Krai',
      'Rostov Oblast',
      'Bashkortostan',
    ],
  },
  {
    name: 'Indonesia',
    states: [
      'Java',
      'Sumatra',
      'Borneo',
      'Sulawesi',
      'West Nusa Tenggara',
      'East Nusa Tenggara',
      'Maluku Islands',
      'Papua',
      'Kalimantan',
      'Jambi',
    ],
  },
  {
    name: 'Pakistan',
    states: [
      'Punjab',
      'Sindh',
      'Khyber Pakhtunkhwa',
      'Balochistan',
      'Gilgit-Baltistan',
      'Azad Jammu and Kashmir',
      'Islamabad Capital Territory',
      'Federally Administered Tribal Areas',
      'Sindh',
      'Punjab',
    ],
  },
  {
    name: 'Nigeria',
    states: [
      'Lagos',
      'Kano',
      'Ibadan',
      'Kaduna',
      'Port Harcourt',
      'Benin City',
      'Maiduguri',
      'Zaria',
      'Abuja',
      'Jos',
    ],
  },
  {
    name: 'Bangladesh',
    states: [
      'Dhaka',
      'Chittagong',
      'Khulna',
      'Rajshahi',
      'Barisal',
      'Sylhet',
      'Rangpur',
      'Comilla',
      'Narayanganj',
      'Gazipur',
    ],
  },
  {
    name: 'Mexico',
    states: [
      'Mexico City',
      'Guadalajara',
      'Monterrey',
      'Puebla',
      'Toluca',
      'Tijuana',
      'Leon',
      'Juarez',
      'La Paz',
      'Cancun',
    ],
  },
]

export default countries
